### PR TITLE
Version 2.2.0

### PR DESCRIPTION
**Pull request by raitisbe**

### CODE REVIEW

**Comment by raitisbe** [comment]
Going to integrate Draw style PR here too when its approved, so might wait a bit with the testing

**Comment by raitisbe** [comment]
I think it's safe to test the last bits before release now.

**Comment by raitisbe** [comment]
> I expect #846 to be merged into develop before the release.

done

**Comment by jmacura** [comment]
[Release 2.2.0](https://trello.com/c/WjVYw3Tb/91-release-220)

**Pull request merged**
