### PR TITLE
Upgrade package-lock to version 2

### PR DESCRIPTION
**Pull request by jmacura**
------------

## Description

Package-lock version 2 is native to npm >=7 and NodeJS >= 16 and shall be backwards-compatible with npm >= 6 (NodeJS >= 10).

## Related issues or pull requests

none

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Dependency updates
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [x] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [x] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Comment by jmacura** [comment]
I am actually unsure about this. This new version of lock-file is auto-generated everytime you install something in an npm repository with npm 7 (packed with Node since v16). I am now using NodeJS 16.7 for some time and haven't encountered any problems with the build (or test). Truth is, I have also switched to using hslayers-test-app instead of symlinked examples repository, so there might be some discrepancies undiscovered...

This change shall be backwards-compatible with Node 10 and higher, but obviously the test run fails here on GitHub. Would be nice if some of you could try it with your setup.

**Comment by raitisbe** [comment]
Yes, I also get this error when running `npm ci`
```
[raitis@archlinux hslayers-ng]$ npm ci
npm ERR! bindings not accessible from webpack-dev-server:fsevents

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/raitis/.npm/_logs/2021-08-31T11_57_42_576Z-debug.log
```

`npm i` kind of works, but reverts package-lock back to version 1

**Comment by raitisbe** [comment]
Tried `npm i fsevents@latest -f --save-optional
` as https://stackoverflow.com/questions/46929196/how-to-solve-npm-install-throwing-fsevents-warning-on-non-mac-os suggests to no avail

**Comment by raitisbe** [comment]
It works now, but got another problem
I currently have npm version 6.14.11 and everytime I do `npm i` the lockfileVersion will be reset back to 1 along with huge amount of changes to lock file. Should we be forcing everybody to upgrade to npm 7?

**Comment by jmacura** [comment]
> 
> 
> It works now, but got another problem
> I currently have npm version 6.14.11 and everytime I do `npm i` the lockfileVersion will be reset back to 1 along with huge amount of changes to lock file. Should we be forcing everybody to upgrade to npm 7?

Unfortunately, it seems like there is no middle ground. Either we encourage usage of latest versions of the software (npm 7 and up) or we encourage usage of stable/legacy software (npm 6 and below).

**Comment by raitisbe** [comment]
Vote here: [](https://api.gh-polls.com/poll/01FENNE30QWZSEYJZWBR8T4JJ9/Npm%207%20LockfileVersion%202/vote)
[](https://api.gh-polls.com/poll/01FENNE30QWZSEYJZWBR8T4JJ9/Npm%206%20LockfileVersion%201/vote)

**Comment by jmacura** [comment]
Oh, that is a marvellous feature 😲

**Comment by jmacura** [comment]
So... I was searching for some recommendations or best-practices but found exactly none.... So I've done a quick GH research (very opinionated):

repository | lock-file version
---------- | ----------------
openlayers | 2
leaflet | none
angular/* | none
cityvizor/client | 2
i18n-ally | 2
maplibre-gl-js | 1
converse.js | 2
converse-desktop | none
iD | none
compodoc | 1
maki | 1
iNaturalistAPI | 1
mapbox/carto | 1
ol-cesium | none
d3 | yarn.lock
cesium | none
lodash | 1
express | none
vue | yarn.lock
tslib | none
webpack | yarn.lock
vscode | yarn.lock
typescript | 1
eslint | none
Babel | yarn.lock
bootstrap | 1
rxjs | 1

Hard to draw some conclusion as I have chosen the repos from my GH-stars + selected some I know from the most popular on npm. But so far it seems that version 2 is only used by some early adopters.

**Review by raitisbe — APPROVED** [review]

**Comment by raitisbe** [comment]
Will have to generate package-lcok again and then I can merge

**Comment by raitisbe** [comment]
Upgraded to version 2 in https://github.com/hslayers/hslayers-ng/commit/1b1ca2a3b521d2cc9bd5c2a112e6d791330ea1d2 so closing this

**Pull request closed without merging**
