### PR TITLE
Update Angular to version 18

### PR DESCRIPTION
**Pull request by jmacura**
## Description
Finally, all necessary packages are ready, so we can update to Angular 18.

## Related issues or pull requests

#4973 

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Dependency updates
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [x] Yes
- [ ] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [x] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [x] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Comment by FilipLeitner** [comment]
Perhaps we could update  "lib": ["es2019", "dom"] in tsconfig.json. es2019 seem to be quite outdated. 

Features of es2022 seem to have a complete support (accros relevant browsers [see](https://caniuse.com/?feats=mdn-javascript_builtins_array_at,mdn-javascript_builtins_regexp_hasindices,mdn-javascript_builtins_object_hasown,mdn-javascript_builtins_error_cause,mdn-javascript_operators_await_top_level,mdn-javascript_classes_private_class_fields,mdn-javascript_classes_private_class_methods,mdn-javascript_classes_static_class_fields,mdn-javascript_classes_static_initialization_blocks)

From [es2023](https://caniuse.com/?feats=mdn-javascript_builtins_array_findlast,mdn-javascript_builtins_array_findlastindex,mdn-javascript_grammar_hashbang_comments,mdn-javascript_builtins_weakmap_symbol_as_keys,mdn-javascript_builtins_array_toreversed,mdn-javascript_builtins_array_tosorted,mdn-javascript_builtins_array_tospliced,mdn-javascript_builtins_array_with)  only Firefox seem to be last one to implement weakmap. We dont use it so it should not be an issue.

What do you think @jmacura  @fzadrazil ?

**Comment by jmacura** [comment]
What would be the benefit for us?
We can always use all the latest features once they are supported in TypeScript language, no matter the output ES version. I always try to keep the output compiled JS code in the oldest version possible, in order to support the widest range of browsers.

**Comment by FilipLeitner** [comment]
> We can always use all the latest features once they are supported in TypeScript language, no matter the output ES version

Well I am not entirely sure I understand. I believe that typescript already support all of the released ECMAScript features but without setting the newer target lib well be getting error such as
image

thats what I was aiming for . Also I think we should be safe to move from 5years old to at least 3 :D

**Comment by jmacura** [comment]
> > We can always use all the latest features once they are supported in TypeScript language, no matter the output ES version
> 
> Well I am not entirely sure I understand. I believe that typescript already support all of the released ECMAScript features but without setting the newer target lib well be getting error such as
> image
> 
> thats what I was aiming for . Also I think we should be safe to move from 5years old to at least 3 :D
> 

Ah, my bad! I thought we are talking about the "target" option in tsconfig 😂 well, in that case, updating the "lib" option to something like "es2022" or "esnext" is quite all right I think.

**Comment by jmacura** [comment]
> 
> Ah, my bad! I thought we are talking about the "target" option in tsconfig 😂 well, in that case, updating the "lib" option to something like "es2022" or "esnext" is quite all right I think.

It was illogical anyway, we had in tsconfig:
```
"target": "ES2022",
"lib": ["es2019", "dom"],
```

so we were targeting actually a newer version of JS than the version we were using in the codebase 😄

**Pull request merged**
