### PR TITLE
Hsl translations

### PR DESCRIPTION
**Pull request by DailisLangovskis**
Complete

### CODE REVIEW

**Comment by raitisbe** [comment]
> Complete

Thank you. I imagine quite a lot of effort went into this.

**Review by raitisbe — APPROVED** [review]

**Comment by jmacura** [comment]
I suspect you expect me to add cs translations, right? :-) I am on it!

**Comment by DailisLangovskis** [comment]
> I suspect you expect me to add cs translations, right? :-) I am on it!

Yes, Thank You!

**Comment by jmacura** [comment]
I found some untranslated strings along the way. You will provide lv translations in return, right? 😉

**Comment by DailisLangovskis** [comment]
> I found some untranslated strings along the way. You will provide lv translations in return, right? 😉

Of course!

**Comment by jmacura** [comment]
> 
> 
> > I found some untranslated strings along the way. You will provide lv translations in return, right? 😉
> 
> Of course!

Hmm.. but it's harder then I expected... Do you have any idea how to translate 'Coordinates' on this line? https://github.com/hslayers/hslayers-ng/blob/e27b6be0d528ef3a88fc078781fb80562590e1a5/components/query/query-base.service.ts#L326

**Comment by jmacura** [comment]
OK, so I guess that's it – it was translated already 😄  Translating "Travel route" and "Waypoint" is over my head now...

**Comment by DailisLangovskis** [comment]
> I found some untranslated strings along the way. You will provide lv translations in return, right? 😉

I don't see any new strings added to json files. Or did You meant untranslated Czech strings?

**Comment by jmacura** [comment]
> 
> 
> > I found some untranslated strings along the way. You will provide lv translations in return, right? 😉
> 
> I don't see any new strings added to json files. Or did You meant untranslated Czech strings? If so, I left them in English intentionally, because it is probably easier for You to do them. than for me. :D
> P.s. LV translations are already there.

It turned out that "coordinates" string was already translated, only not used. And I gave up trying to translate the other non-i18n strings. So no job for you in the end.

**Comment by jmacura** [comment]
And a side-note to the formatting: I add the new-lines intentionally. Or... my editor does. Do you have "EditorConfig for VS Code" extension installed? Because we have the `insert_final_newline = true` in our .editorconfig settings...

**Review by jmacura — APPROVED** [review]
🚀

**Comment by DailisLangovskis** [comment]
> And a side-note to the formatting: I add the new-lines intentionally. Or... my editor does. Do you have "EditorConfig for VS Code" extension installed? Because we have the `insert_final_newline = true` in our .editorconfig settings...

I have default. But I did not check the changes :D Just did format ad sort commands. Pushed everything in and that is it.

**Comment by DailisLangovskis** [comment]
> > > I found some untranslated strings along the way. You will provide lv translations in return, right? 😉
> > 
> > 
> > I don't see any new strings added to json files. Or did You meant untranslated Czech strings? If so, I left them in English intentionally, because it is probably easier for You to do them. than for me. :D
> > P.s. LV translations are already there.
> 
> It turned out that "coordinates" string was already translated, only not used. And I gave up trying to translate the other non-i18n strings. So no job for you in the end.

Probably will be adding translations layer on for the strings inside .ts files and so on. When it will be more urgent.

**Pull request merged**
