### PR TITLE
build: Upgrade OL to v10 & geostyler packages to new versions and adjust type definitions

### PR DESCRIPTION
**Pull request by FilipLeitner**
## Description

- Upgrade OL to v10 along with neccessary changes
- Upgrade geostyler packages to new major versions
- Properly initiate layer styles when style is defiend as OL style ( OL style to SLD parsing)

## Related issues or pull requests

Superseeds #5104 #5068 #5067 #5049 #5047

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [x] Yes
- [ ] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [ ] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [ ] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Comment by jmacura** [comment]
Ah... Changing the VectorSource types back and forth... 🙄

**Comment by FilipLeitner** [comment]
> Ah... Changing the VectorSource types back and forth... 🙄

Well :D unless I made some mistake than yes. Seems a bit like an side effect of trying to keep typing [cosistent ](https://github.com/openlayers/openlayers/pull/15869#issuecomment-2132397184)and to [improve UX ](https://github.com/openlayers/openlayers/pull/15869#discussion_r1622522940)

**Comment by jmacura** [comment]
> > Ah... Changing the VectorSource types back and forth... 🙄
> 
> Well :D unless I made some mistake than yes. Seems a bit like an side effect of trying to keep typing [cosistent ](https://github.com/openlayers/openlayers/pull/15869#issuecomment-2132397184)and to [improve UX ](https://github.com/openlayers/openlayers/pull/15869#discussion_r1622522940)

Aye. It will produce breaking changes in all HSL applications. So I am thinking whether we shall treat it as such and increase the version number to 15 at any upcoming release 🤔 What do you think, @FilipLeitner ?

**Comment by FilipLeitner** [comment]
> > > Ah... Changing the VectorSource types back and forth... 🙄
> > 
> > 
> > Well :D unless I made some mistake than yes. Seems a bit like an side effect of trying to keep typing [cosistent ](https://github.com/openlayers/openlayers/pull/15869#issuecomment-2132397184)and to [improve UX ](https://github.com/openlayers/openlayers/pull/15869#discussion_r1622522940)
> 
> Aye. It will produce breaking changes in all HSL applications. So I am thinking whether we shall treat it as such and increase the version number to 15 at any upcoming release 🤔 What do you think, @FilipLeitner ?

Well I guess you are right. There will be need to do some manual changes which makes for a major version increment.

**Review by jmacura — APPROVED** [review]
Awesome, it will close several blocked PRs 👍

**Pull request merged**
