### PR TITLE
fix: Use dynamic asset path for default styler icons

### PR DESCRIPTION
**Pull request by raitisbe**

### CODE REVIEW

**Comment by raitisbe** [comment]
I switched hslayers on server to this branch. Getting Forbidden errors for https://hub.lesprojekt.cz/hsl-ng/git/hslayers-ng/dist/hslayers-app/assets/img/icons/gps43.svg but should work

**Comment by jmacura** [comment]
The behaviour can be a bit different from what I have done in #1983 . What if I merge this branch to that branch and then synchronize the code a little?

**Comment by raitisbe** [comment]
@jmacura COuld do yes, if you think my changes bring some added benefits. For fixing the error your changes are enough.

**Comment by fzadrazil** [comment]
> Getting Forbidden errors for https://hub.lesprojekt.cz/hsl-ng/git/hslayers-ng/dist/hslayers-app/assets/img/icons/gps43.svg

I have fixed the permissions and the icons works fine now.

**Pull request closed without merging**
