### PR TITLE
Upload QML (Issue 3433)

### PR DESCRIPTION
**Pull request by raitisbe**
## Description

Support upload of QML in style panel and create a walkaround for invalid WellKnownName problem when parsing qml with geostyler-qml-parser.

## Related issues or pull requests

https://github.com/hslayers/hslayers-ng/issues/3433
https://github.com/hslayers/hslayers-ng/issues/3431

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [x] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [x] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [x] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [ ] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Review by jmacura — CHANGES_REQUESTED** [review]
~~image
This is now in the console, when I start the test-app. I believe it was not there before...~~

UPDATE: Forgotten `npm i`

**Review by jmacura — CHANGES_REQUESTED** [review]
Not much has changed regarding #3431
image
Only now when I add the layer "bioregion_pilots" from the data catalogue as WFS, all layers disappear from the map 😱 
image

**Comment by raitisbe** [comment]
Yes, getcolor was added back in ol-ext just in the latest ol-ext version.
Dicd you npm ci?

**Comment by jmacura** [comment]
> Yes, getcolor was added back in ol-ext just in the latest ol-ext version. Dicd you npm ci?
> […](#)

Good point. My apologies. I have updated the comments above.

**Comment by raitisbe** [comment]
> Not much has changed regarding #3431 image Only now when I add the layer "bioregion_pilots" from the data catalogue as WFS, all layers disappear from the map scream image

Right, I actually only fixed it when uploading the SLD to style pannel. Not for loading the layer from `add-data`

**Comment by raitisbe** [comment]
@jmacura could you retest please?

**Comment by jmacura** [comment]
Sure, will test it later today.

**Review by jmacura — COMMENTED** [review]
The good news is that the error is gone 👏 

This is how the styled layer looks like now.
image
Whereas it should look like this.
image

Not sure if it is an acceptable behaviour 😄

**Comment by jmacura** [comment]
The reason is that the Text Symbolizer is malformed.

The template for displaying the text is
image

whereas the correct formula should be
image

Not sure if we can fix this. I have to check what is actually stored in the layer's style..

**Comment by jmacura** [comment]
And... We can't. There is a TODO note in the code of geostyler/geostyler-qgis-parser: https://github.com/geostyler/geostyler-qgis-parser/blob/ae5203392377d2342ef04a50766eedcdfe5990ec/src/QGISStyleParser.ts#L405
Expession based labels are not supported.

Hence I think this PR is an acceptable fix.

**Review by jmacura — CHANGES_REQUESTED** [review]
Would you mind changing the last commit message to something better than "squash", @raitisbe ? 🙏 🙂

**Review by jmacura — COMMENTED** [review]
One more thought...
If we will also allow to upload the QML style fils along with a new layer in the Datasources panel, will it work out of the box now?
image

**Review by jmacura — APPROVED** [review]
We can also implement the upload of QML along with new vector layer later on.

**Comment by raitisbe** [comment]
> long with new vector layer later on.

I did it in this PR, but It had so many changes I'm not sure I haven't broken something... Especially on the upload to Layman side. I think we will need to have some e2e test for this

**Comment by jmacura** [comment]
> > long with new vector layer later on.
> 
> I did it in this PR, but It had so many changes I'm not sure I haven't broken something... Especially on the upload to Layman side. I think we will need to have some e2e test for this

Aye. That is what I was afraid of. Actually I started to implement it after our telco today, but then I have realised I am lost, as I do not know the consequences on the Layman side so I have thrown my changes away.
Will test your changes, thanks!

**Review by jmacura — APPROVED** [review]
Works like a charm 🚀 
image

**Pull request merged**
