### PR TITLE
Release 2.3.0

### PR DESCRIPTION
**Pull request by jmacura**
As mentioned at the last Friday's telco, I propose to make a new release in the 2.x series.
We already have quite a lot of changes in the code.
I would also make good use of it in the polirural clustering app.

Only #958, #940 and dependency updates shall be merged before this release. Other PRs can part of the next one.

### CODE REVIEW

**Comment by raitisbe** [comment]
agree, 210 commits 🌊

**Comment by jmacura** [comment]
[Release 2.3.0](https://trello.com/c/Fop1pKrV/101-release-230)

**Comment by jmacura** [comment]
If #972 is not replicable, then we can finally merge this PR and create the release.
Any objections @fzadrazil @FilipLeitner ?

**Comment by fzadrazil** [comment]
It is fine with me. No objections.

**Review by fzadrazil — APPROVED** [review]

**Pull request merged**
