### PR TITLE
Store SLD change per layer + missing SK translations

### PR DESCRIPTION
**Pull request by FilipLeitner**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Dependency updates
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [x] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [ ] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [ ] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [ ] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Comment by raitisbe** [comment]
Could you please squash my commit with [cce6344](https://github.com/hslayers/hslayers-ng/pull/3299/commits/cce6344461773595e27922fedf93007542129e72) @FilipLeitner

**Comment by FilipLeitner** [comment]
> Could you please squash my commit with [cce6344](https://github.com/hslayers/hslayers-ng/pull/3299/commits/cce6344461773595e27922fedf93007542129e72) @FilipLeitner

Sure, and thanks for the improvement. It felt weird to use ['ol_uid'] right away; I just somehow didn't find the method in docs :D

**Review by raitisbe — APPROVED** [review]

**Comment by raitisbe** [comment]
merging?

**Comment by FilipLeitner** [comment]
Sure

**Pull request merged**
