### PR TITLE
Allow adding Arcgis Image Services to map (Issue 2574)

### LINKED ISSUE #2574: ArcGIS image services
# Feature Request

Image services are currently allowed to be entered in the add data panel and listed when adding whole services, but doesn't work.

**Describe the solution you'd like**
As described in #2459 there are more types of map services in ArcGIS. ImageServer services are similar to tiled MapServer, but without layers inside it. Should be created as OL ImageArcGISRest.

**Additional context**
Sample services
http://ags.cuzk.cz/arcgis/rest/services/3D/dmr4g_wm/ImageServer
https://sampleserver6.arcgisonline.com/arcgis/rest/services/Elevation/earthquakedemoelevation/ImageServer

### PR DESCRIPTION
**Pull request by DailisLangovskis**
## Description

This PR resolves #2574 

## Related issues or pull requests

closes #2574 

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [x] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [x] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [x] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Review by fzadrazil — CHANGES_REQUESTED** [review]
Exclude geoprocessing (GPServer) services from the list, eg. https://sampleserver6.arcgisonline.com/arcgis/rest/services/Elevation/

**Comment by fzadrazil** [comment]
When MapServer and ImageServer services are selected at one time from the service list, only the ImageServer gets added to the map.

**Comment by fzadrazil** [comment]
> When MapServer and ImageServer services are selected at one time from the service list, only the ImageServer gets added to the map.

That works now! 👍  But when you directly click on the ImageServer in the list of services, nothing happens, only the list disappeares.

**Comment by fzadrazil** [comment]
> Fixed the first pointed out issue, but the zoom is not working, because Ol does not recognize the projection provided.

Ah, you are right. I wonder why is that. But works for other services with more usual CRS.
But there is still one more issue. When selecting two image services from here, only the first one is added
http://ags.cuzk.cz/arcgis/rest/services/3D

**Comment by DailisLangovskis** [comment]
> > Fixed the first pointed out issue, but the zoom is not working, because Ol does not recognize the projection provided.
> 
> Ah, you are right. I wonder why is that. But works for other services with more usual CRS. But there is still one more issue. When selecting two image services from here, only the first one is added http://ags.cuzk.cz/arcgis/rest/services/3D

Resolved

**Review by fzadrazil — APPROVED** [review]

**Pull request merged**
