### PR TITLE
Public API + refactoring

### PR DESCRIPTION
**Pull request by jmacura**
------------

## Description
Multitude of wide refactoring changes related (more or less) to #2111 

## Related issues or pull requests

#2111 

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Dependency updates
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [ ] No
- [x] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [x] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Comment by jmacura** [comment]
All our services are provided in 'root' by default, i.e. they are not coupled with any particular module.
Only exceptions are:
* EndpointsWithDatasourcesPipe which is a Pipe also used as a service inside another service (sounds horrible but works)
* HsConfig
* HsLayerUtilsService
* HsUtilsService
the latter three can be probably also provided globally, but for now I have kept the status quo.

**Comment by jmacura** [comment]
On the exports. The primary public-api was split into separate public-api files in each sub-module for easier maintanance. Now everything is export for public. All
* components
* modules
* services
* pipes
* interfaces
* plain classes and
* types.

Only spec-files and mock-files are not exported + `backwards-compatibility.ts` file from styler.

**Comment by raitisbe** [comment]
Can we merge this as soon as possible? it seems to be quite safe from the first glance at the changes and also tests are completing.

**Comment by jmacura** [comment]
Well, yes, I would just like to hear your opinion about the public exports. Whether it is OK to expose 100% of the code to the consumers, or whether we want to keep some services/pipes/types/anything for internal use only. @raitisbe @fzadrazil perhaps @FilipLeitner @DailisLangovskis but can be also important for @SLeitgeb @ChcJohnie ..?

Beside that I am fine with merging, we can do more refinement later on.

**Comment by DailisLangovskis** [comment]
> Well, yes, I would just like to hear your opinion about the public exports. Whether it is OK to expose 100% of the code to the consumers, or whether we want to keep some services/pipes/types/anything for internal use only. @raitisbe @fzadrazil perhaps @FilipLeitner @DailisLangovskis but can be also important for @SLeitgeb @ChcJohnie ..?
> 
> Beside that I am fine with merging, we can do more refinement later on.

I have no problem with giving 100% to public! :)

**Comment by raitisbe** [comment]
> Well, yes, I would just like to hear your opinion about the public exports. Whether it is OK to expose 100% of the code to the consumers, or whether we want to keep some services/pipes/types/anything for internal use only. @raitisbe @fzadrazil perhaps @FilipLeitner @DailisLangovskis but can be also important for @SLeitgeb @ChcJohnie ..?
> 
> Beside that I am fine with merging, we can do more refinement later on.

Theres nothing secret. The only rationalle was to not overload the mental capabilities of consumers of the API :) Also we would need to document everything we expose at some point, but yes it's safer to expose everything not to forget something.

**Review by raitisbe — APPROVED** [review]

**Comment by jmacura** [comment]
Great, I also support the publicity :-) Yet it's worth the note that it has some side-effect for us: When everything is part of a public API, then every renamed/deleted/moved function, method or even class property variable shall be considered a breaking change 😵

**Comment by raitisbe** [comment]
> Great, I also support the publicity :-) Yet it's worth the note that it has some side-effect for us: When everything is part of a public API, then every renamed/deleted/moved function, method or even class property variable shall be considered a breaking change

Can't we reexport the lower level public_apis into root 'hslayers-ng' public api thus making it nonbreaking? Or does it somehow interfere with the treeshaking? I also noted that inside our modules when using import {HsPanelComponent} from '../layout/public-api' it created a circular reference, but a more speciffic `import {HsPanelComponent} from '../layout/panels/panel-component.interface'`; was working fine. Must be carefull with the automatically generated imports.

**Comment by jmacura** [comment]
> 
> 
> > Great, I also support the publicity :-) Yet it's worth the note that it has some side-effect for us: When everything is part of a public API, then every renamed/deleted/moved function, method or even class property variable shall be considered a breaking change
> 
> Can't we reexport the lower level public_apis into root 'hslayers-ng' public api thus making it nonbreaking?

This is not a problem at all. For a consumer, the internal structure of our repo is obscured. As a consumer, you just `import {HsPanelComponent} from 'hslayers-ng'` no matter in which sub-directory it resides. The problem is, when you make an app where you have code like
```
import {HsPanelContainerService} from 'hslayers-ng'
...
constructor(
    public hsPanelContainerService: HsPanelContainerService,
  )
...
this.hsPanelContainerService.destroy(somePanel);
```
and then we suddenly decide that `demolish()` could be a better naming then `destroy()`, so we rename, and the app is broken. The same happens when we move the `destroy()` method into some other service or just rename the service. Dumb example perhaps but I guess you get the point 😉

**Pull request merged**
