### PR TITLE
Geometric operations in Drawing

### LINKED ISSUE #2386: Geometric operations in Drawing
# Feature Request

**Describe the solution you'd like**
Add more tools to drawing for polygons like

- split polygon by polyline
- union
- intersection
- difference
- (symetrical difference)?

### PR DESCRIPTION
**Pull request by FilipLeitner**
## Description

- Implement geometric operations(difference, union, intersect, 'cut by line') to drawing panel
- Some perf improvements

## Related issues or pull requests

closes #2386 

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [x] Yes
- [ ] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [x] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Comment by FilipLeitner** [comment]
> @FilipLeitner Inside the edit panel, using split and having selected at least 2 feature, I am getting this error -> err
> 
> P.S Added lv translations

Thanks! For translation and also for a quick test. It still needs some fine tuning for sure.

**Comment by jmacura** [comment]
After some testing of the "splitting" tool, I have reached the point where two polygons seemed to be split, but were clickable only as a whole and the editing panel was not showing anything.
image

There were several errors in the console.
image
etc.

**Comment by FilipLeitner** [comment]
Thanks for the translations and testing @jmacura !  Hopefully ill be able to replicate and fix

**Comment by FilipLeitner** [comment]
Added few new fixes  but I could not replicate the bug u found @jmacura .

**Comment by jmacura** [comment]
> Added few new fixes but I could not replicate the bug u found @jmacura .

Try to split the polygon and union it again. I always end up with some unexpected results after several repetitions.
image

**Comment by jmacura** [comment]
Ah, I think this has something to do with snapping. When I draw the split line with as snapped to one of the corners, it actually does not take the coordinates of the corner, it only visually "snaps" the line, but it is not really intersecting the polygon.

image
image

**Comment by jmacura** [comment]
And is it possible to disable editing of other features when drawing the intersection features? It is annoying to move vertices of the underlaying polygons when you actually want to draw something over them.
image

**Comment by FilipLeitner** [comment]
Trying to union features that have been split is not really possible right now because there is actually a gap between the split parts of the original geometry
image
even after using 0.001 meterr as a line buffer distance (the edege of the polygon seems ti be visually bugged becuase moving a single vertex smoothen  the line immediately. Also there are no vertexes for each of the 'bumps'
image

It would be possible to create multipolygon with the little gap but that complicates everything....other solution that came to my mind is to look for a way to buffer features that user want to union by the same distance we 'buffer' splitting line. Maybe even

You are right about the snap intearction.  Ill try to turn it off same with the editing

**Comment by raitisbe** [comment]
> Trying to union features that have been split is not really possible right now because there is actually a gap between the split So if I understand correctly the split polygons are not topologically correct i.e. don't have a common point?

**Comment by FilipLeitner** [comment]
> > Trying to union features that have been split is not really possible right now because there is actually a gap between the split So if I understand correctly the split polygons are not topologically correct i.e. don't have a common point?

Exactly

**Review by raitisbe — APPROVED** [review]

**Pull request merged**
