### PR TITLE
Simple form removal (Issue 2676)

### LINKED ISSUE #2676: Save-map simple form
# Bug

**Describe the bug**
Config parameter advancedForm: false toggles 'simple form' for saving compositon. However this component is not working, UI bugged also:
- advanced options menu not opening
- auth warning visible when logged in
- thumbnail not working
- save button always disabled

**To Reproduce**
1. Set advancedForm config option to 'true'
2. Run app
3. Open 'Save map' panel

**Expected behavior**
Its possible to save current map state to composition

**Screenshots**
image

**Additional context**
Simple form should be fixed or removed

### PR DESCRIPTION
**Pull request by DailisLangovskis**
## Description

Removes simple form component from save-map module and removed advancedForm hsConfig parameter.

## Related issues or pull requests

closes #2676 

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [x] Yes
- [ ] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [x] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Comment by DailisLangovskis** [comment]
@FilipLeitner Can You do some testing? Also the thumbnail displays ok, but after saving and opening compositions metadata, thumbnail is missing multiple layers. Only one ol-layer canvas is saved

**Comment by FilipLeitner** [comment]
Tried playing around a bit and what I lack are some UX features. 
- let user know why hes not able to click 'Save' right away (there is an asterisk but its not quite enough I guess). For example instead of disabling save button we could color missing required inputs red (something those reactive forms would be good at :D )
- something simmilar for the case when user wants to rename composition
+ .+ about author information doesnt seem to be saved anywhere. I filled every single one of them for [this comp](https://hub.lesprojekt.cz/micka/record/basic/m-9f209e51-34b4-4daf-b010-6864e38a0351)

**Comment by FilipLeitner** [comment]
> @FilipLeitner Can You do some testing? Also the thumbnail displays ok, but after saving and opening compositions metadata, thumbnail is missing multiple layers. Only one ol-layer canvas is saved

Actually thumbnail generated in save-map is not sent to layman at all.  I think thumbnail is being generated based based on bbox . Regarding layers visible in it, from what I observed it seems like only some of WMS service layers are making it to thumbnail

**Comment by raitisbe** [comment]
There used to be the problem that layers are rendered on separate canvas
and a subsequent fix which loops through them and does compositing. Maybe
got broken at some time

**Review by raitisbe — APPROVED** [review]

**Pull request merged**
