### PR TITLE
Issue 735/convert to ts

### PR DESCRIPTION
**Pull request by raitisbe**
I did the renaming of files to *.ts in the last 2 commits, but dont know how to not drag all the rest of the commits for rewrite to ng9 along :(

### CODE REVIEW

**Comment by jmacura** [comment]
If I understand it correctly, all HSLayers-based applications will immediately stop working after this change (when released, of course), until they install TS and ts-loader as well.

**Comment by FilipLeitner** [comment]
> I did the renaming of files to *.ts in the last 2 commits, but dont know how to not drag all the rest of the commits for rewrite to ng9 along :(

Hmm, maybe cherry pick would work for this. https://git-scm.com/docs/git-cherry-pick

**Comment by raitisbe** [comment]
@jmacura Yes, the ones which don't the hslayers bundle, but compile the whole app with webpack.

**Comment by raitisbe** [comment]
@FilipLeitner  No no, cherry picking is evil and not sustainable :) I guess if I based this branch on develop branch, it would have been ok, but develop doesn't yet support typescript and angular until https://github.com/hslayers/hslayers-ng/pull/732 is merged

**Pull request merged**
