### PR TITLE
refactor: Info component style tweaks

### LINKED ISSUE #3437: Additional panels text & icons not aligned
# Bug

**Describe the bug**
In the additional panels "panel", the text is not centred as the icons are.

**To Reproduce**
1. Go to 'Additional panels'
2. See

**Expected behavior**
Text right under the icon

**Screenshots**
image

**Additional context**
none

### PR DESCRIPTION
**Pull request by FilipLeitner**
## Description

Small info component style tweaks based on #3412. 

## Related issues or pull requests

closes #3437 

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [x] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [ ] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [ ] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [ ] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Review by jmacura — COMMENTED** [review]
Thanks for the changes, I really like them!

One afterthought: This might be a bit confusing now. Can we came up with a different icon for one of those?
image

**Comment by FilipLeitner** [comment]
> Thanks for the changes, I really like them!
> 
> One afterthought: This might be a bit confusing now. Can we came up with a different icon for one of those? image

hmmm :D to be honest I don't even know what that lower icon should symbolize. I don't think I have seen it ever before. But sure its not a good idea to have it there twice

**Comment by jmacura** [comment]
> > Thanks for the changes, I really like them!
> > One afterthought: This might be a bit confusing now. Can we came up with a different icon for one of those? image
> 
> hmmm :D to be honest I don't even know what that lower icon should symbolize. I don't think I have seen it ever before. But sure its not a good idea to have it there twice

Yes, I don't see it often either. I think it symbolizes that you are working with a saved composition. But I would have to check the code to be sure. It appeared when I opened a composition from the Compositions panel.

**Comment by FilipLeitner** [comment]
Well :D ..and yes its shown hen composition is loaded
image

**Comment by FilipLeitner** [comment]
Makes sense.  Regarding the newly found icon inside ifno component, I don't really find it useful. We could make a change such as this for example 
image

**Comment by jmacura** [comment]
For basemap-gallery, these might be suitable I think:

- icon-th-large
- icon-layersalt
- icon-magazine
- icon-sendbackward
- icon-sendtoback
- icon-pigpenk
- icon-pigpenb

Any other ideas, @FilipLeitner ? What about opening a poll in the discussions again?

**Comment by FilipLeitner** [comment]
Sure Ill make one

**Comment by jmacura** [comment]
> 
>   * get rid of icon (what do you think @fzadrazil )
> 
>   * add string 'Composition:'  to indicate its title of composition
> 
>   * truncate text and limit element size

I am in favour of these changes. The icon can be kept in the beginning of the headline, reduced to text-size, if we feel like it's helpful to UX.

**Comment by FilipLeitner** [comment]
#3442

**Comment by FilipLeitner** [comment]
Pretty much all the states possible. 
PS: already fixed width difference between composition name box and loading layers

Wondering about 'New map' width. Wether it should be the same width as the rest of the elements or as in the picture because its rather short text so it would
image

**Comment by jmacura** [comment]
Ready to merge, @FilipLeitner ?

**Comment by FilipLeitner** [comment]
>Ready to merge

Yes

**Pull request merged**
