### PR TITLE
Update ESLint settings

### PR DESCRIPTION
**Pull request by jmacura**
Delete useless .gitkeep
Change angular/typecheck-* rules
Return .vscode/ under VCS
Ignore dist/ in ESLint
Add eslint-plugin-jsdoc

### CODE REVIEW

**Comment by jmacura** [comment]
[Lint modules](https://trello.com/c/6Bg4rPbU/52-lint-modules)

**Comment by raitisbe** [comment]
I think we should not put .vscode under source control because its user speciffic. Can't we have it as a template or put the settings in another file?

**Comment by jmacura** [comment]
See https://stackoverflow.com/questions/32964920/should-i-commit-the-vscode-folder-to-source-control

**Comment by jmacura** [comment]
@raitisbe Having the project-settings shared between collaborators prevents odd misbehaviour.
I don't think we should be using it though. I have no .vscode/ in the HSLayers folder for example. Everything that it can be useful for (line-lenght, line-endings, ...) is already set by eslint rules and now by prettier rules specifically.

**Comment by raitisbe** [comment]
I had exactly the same thought a year ago, but added .vscode to ignore
list because i was using some settings which realy were messing with looks
on Simons computer. Line length guide in a form of vertical line for
example :)

**Comment by jmacura** [comment]
Superceded by #648

**Pull request closed without merging**
