### PR TITLE
Issue 357 - GeoTiff support

### PR DESCRIPTION
**Pull request by DailisLangovskis**
## Description

This PR introdoces new geotiff component for add-data panel, in order to upload geotiff images to openlayers map.
## Related issues or pull requests

refs #357

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [x] Dependency updates
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [x] Yes
- [ ] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [x] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [x] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Comment by jmacura** [comment]
SK translations awaiting @FilipLeitner 😉

**Comment by DailisLangovskis** [comment]
> SK translations awaiting @FilipLeitner 😉

**Review by raitisbe — APPROVED** [review]

**Comment by raitisbe** [comment]
I was getting 
```
{access_rights: {read: ["raitisbe", "EVERYONE"], write: ["raitisbe"]},…}
access_rights: {read: ["raitisbe", "EVERYONE"], write: ["raitisbe"]}
bounding_box: [null, null, null, null]
description: ""
file: {error: {code: 50, message: "Error when normalizing raster file"}, file_type: "raster",…}
error: {code: 50, message: "Error when normalizing raster file"}
file_type: "raster"
path: "layers/mos_eu_laea_2000/input_file/mos_eu_laea_2000.tif"
status: "FAILURE"
```
from layman though. Did you encounter this?

**Comment by raitisbe** [comment]
Seems that we will need to handle the errors returned by layman with some toast messages. Can be another PR

**Comment by DailisLangovskis** [comment]
> I was getting
> 
> ```
> {access_rights: {read: ["raitisbe", "EVERYONE"], write: ["raitisbe"]},…}
> access_rights: {read: ["raitisbe", "EVERYONE"], write: ["raitisbe"]}
> bounding_box: [null, null, null, null]
> description: ""
> file: {error: {code: 50, message: "Error when normalizing raster file"}, file_type: "raster",…}
> error: {code: 50, message: "Error when normalizing raster file"}
> file_type: "raster"
> path: "layers/mos_eu_laea_2000/input_file/mos_eu_laea_2000.tif"
> status: "FAILURE"
> ```
> 
> from layman though. Did you encounter this?

No I haven't encountered this one.

**Comment by DailisLangovskis** [comment]
> Seems that we will need to handle the errors returned by layman with some toast messages. Can be another PR

Will do!

**Pull request merged**
