### PR TITLE
Ability to toggle all layer visibility (Issue 2585)

### LINKED ISSUE #2585: Allow to turn all layers on/off
# Feature Request

**Is your feature request related to a problem? Please describe.**
When many layers are present in the LayerManager and the user wants to change a visibility of all of them at once, they now have to click at each line one by one. Not very UX friendly.
image

**Describe the solution you'd like**
Either
a) add a new button on top which will turn all layers on/off (base-layers excluded),
image
b) add a new button on top of each section (folder) which will turn only those layers on/off,
image
c) add a keyboard shortcut combination like 'CTRL' + click or 'SHIFT' + click which will do the same as (a) or (b).

**Describe alternatives you've considered**
All alternatives listed above.

### PR DESCRIPTION
**Pull request by DailisLangovskis**
## Description

Resolves issue #2585 

## Related issues or pull requests

closes #2585 

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Dependency updates
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [x] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [x] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [x] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Comment by jmacura** [comment]
obrazek
Nice!
Perfectionists would like to align the text pixel-wise 😉

**Comment by jmacura** [comment]
obrazek
Better, isn't it?

**Review by jmacura — APPROVED** [review]
After filling in sk translation (@FilipLeitner ) it's good to go from my POV.

👍 for including unit tests

**Comment by DailisLangovskis** [comment]
> After filling in sk translation (@FilipLeitner ) it's good to go from my POV.
> 
> 👍 for including unit tests

Well I18N ALLY shows me still 9 CS missing translations as well

**Pull request merged**
