### PR TITLE
Add missing translations

### PR DESCRIPTION
**Pull request by FilipLeitner**

### CODE REVIEW

**Comment by jmacura** [comment]
Some strings are not translatable
image
image
image

**Comment by FilipLeitner** [comment]
History of this branch is a bit 'broken' after the force push.

**Comment by FilipLeitner** [comment]
Merged https://github.com/hslayers/hslayers-ng/tree/issue-1502-transalations and https://github.com/hslayers/hslayers-ng/tree/issue-1502/layer-type properly here 
https://github.com/hslayers/hslayers-ng/tree/1502-translation. We could maybe create a PR from that branch instead. Or force push your PR branch to that?

**Comment by jmacura** [comment]
> 
> 
> Merged https://github.com/hslayers/hslayers-ng/tree/issue-1502-transalations and https://github.com/hslayers/hslayers-ng/tree/issue-1502/layer-type properly here
> https://github.com/hslayers/hslayers-ng/tree/1502-translation. We could maybe create a PR from that branch instead. Or force push your PR branch to that?

The history is fixed now (I guess it was my bad, a bit complicated to describe). I also dared to reword your commit msg ("transalations" to "translations") 😉

**Comment by jmacura** [comment]
I have added few more strings, if you could take a look at LV/SK, @DailisLangovskis @FilipLeitner 🥺

**Review by jmacura — APPROVED** [review]
Thank you both!

**Pull request merged**
