### PR TITLE
Decoupling

### PR DESCRIPTION
**Pull request by raitisbe**
## Related issues or pull requests

https://github.com/hslayers/hslayers-ng/issues/2111

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Dependency updates
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [x] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [ ] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [ ] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Comment by jmacura** [comment]
Do you intend to keep the new testing app, @raitisbe ?

**Comment by raitisbe** [comment]
> Do you intend to keep the new testing app, @raitisbe ?

I dont see any other way. Could be used as a project for e2e testing.

**Review by DailisLangovskis — COMMENTED** [review]
Tried running all of our apps and only decoupling-test-app and test-app compiled and displayed a result app.

**Comment by raitisbe** [comment]
thanks

**Pull request merged**
