### PR TITLE
perf: Remove usage of panelSpaceWidth function

### PR DESCRIPTION
**Pull request by FilipLeitner**
## Description

Because panelSpaceWidth function is called on every digest cycle twice so I tought it might be quite beneficial for us to replace it with something more efficient which would be css. The problematic part is that the new approach must be able to handle dynamicaly created panel that are not part of the library which makes panel specific css classes unusable .
So I tought we might make a little trade off of absolute freedom of width declaration using for example 14 predefined 'size classes' generated like so:
```
    @for $i from 0 through 14{
      .hs-panelspace hs-panel-container .hs-panelWidth-#{400 + ($i * 25) } {
        width: 400 + ($i * 25)+px;
      }

      //Output:
      .hsl .hs-panelspace hs-panel-container .hs-panelWidth-400 {
          width: 400px;
        }
      .hsl .hs-panelspace hs-panel-container .hs-panelWidth-425 {
        width: 425px;
      }
      ....
```
These would be added to the panel element while being created -> based on `panelWidth` property of `data` argument in `hsPanelContainerService.create`  eg.:

- ` this.HsPanelContainerService.create({ component: AnyComponentClass });`

One problematic aspect I should point out is **how to find the right element** on which we add class onto. Basically looking for the element with `[hidden]=isVisible()`. However it doesnt necessarily need to be a first element (eg. query component) or div.
```
      componentRef.location.nativeElement.children[0].classList.add(
        `hs-panelWidth-${Math.round(panelItem.data.panelWidth / 25) * 25}`
      );
```
We cant use the host element of component because panel space would get the width from the most broad one.. 

So lets see maybe we can put it together somehow

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [x] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [x] Yes
- [ ] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [x] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [x] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Comment by DailisLangovskis** [comment]
@FilipLeitner Maybe the width panel param, could be optional and there could be a default value, if no width is provided?

**Comment by FilipLeitner** [comment]
> @FilipLeitner Maybe the width panel param, could be optional and there could be a default value, if no width is provided?

`min-width: 400px` on panelspace class should acts as an fallback .
And about the width param, I was thinking about adding it as a standalone param but we would have two optionals then so I just added it inside existing data object.....but maybe with interface it would be also be more clear how to define the width.. Will change that

**Comment by jmacura** [comment]
> So I tought we might make a little trade off of absolute freedom of width declaration using for example 14 predefined 'size classes'

A while ago (can be a year or more) we even discussed whether we should not remove this freedom for good and stick to uniform width for all the panels. Whereas every content that is too wide to be displayed in the panel shall be displayed in a dialog window. Just recalling what was said. I do not have strict opinion about it as of now.

**Comment by raitisbe** [comment]
Freedom's good, don't we love freedom? :)

**Comment by jmacura** [comment]
> Freedom's good, don't we love freedom? :)

We don't. That's why we use TypeScript and ESLint, to put an order in place ;-)

**Comment by FilipLeitner** [comment]
After all mostly to prevent breaking changes some changes were made and panel width defintion will stay inside HsConfig (panelWidths)

**Comment by raitisbe** [comment]
I have the problem that `componentRef.location.nativeElement.children` is empty, ebcause the nativeElement only contains one comment line `<!--container-->`. You can see it in hsl-7 branch of hslayers/applications AgroInfo.

image

**Comment by FilipLeitner** [comment]
`<div *ngIf="isVisible()">` on that element. Dont remember exactly why I went with ngIf instead of just [hidden] but Id say it should be possible to use hidden. But ye if its empty then the class will not be added

**Comment by raitisbe** [comment]
Lets have hs-panel-width- instead of hs-panelWidth- ?

**Review by raitisbe — APPROVED** [review]

**Pull request merged**
