### PR TITLE
Develop material

### PR DESCRIPTION
**Pull request by SLeitgeb**

### CODE REVIEW

**Comment by raitisbe** [comment]
The map doesn't fill the whole screen. 
image

I dont realy understand this `style="--vh:4.46px;"` which gets set everywhere dynamiccally by material I guess.

style="height: 100vh" on body solves it, but seems a bit extreme.

**Comment by SLeitgeb** [comment]
Yes, it behaves strangely, something broke it during merge, I will investigate further this week.

**Review by raitisbe — APPROVED** [review]

**Comment by jmacura** [comment]
I appreciate the numerous tests you have set up @SLeitgeb 👍 
What I dislike is the usage of TSLint, which is generally discouraged in favour of ESLint.

**Comment by SLeitgeb** [comment]
> What I dislike is the usage of TSLint, which is generally discouraged in favour of ESLint.

Thanks for the feedback, migrated to ESLint in https://github.com/hslayers/hslayers-ng/commit/4f0220adb8fb8b353b54f0ab820c748d1fe3c3c5
Does this seem OK to you?

**Comment by jmacura** [comment]
Great! It seems OK, but I still have some questions/comments.
- pushing to develop branch directly is discouraged. We shall discuss this further.
- some dependencies has been downgraded. Is there a reason for it?
- new dependencies are pinned at very specific versions ("4.3.0" instead of semver-compatible "^4.3.0"). Is there a reason for it?
- some dependencies seem useless to me ("eslint-plugin-jsdoc", "eslint-plugin-prefer-arrow"). Are they required by some of your tools?

**Comment by SLeitgeb** [comment]
Well, I'm using Angular tooling to manage the dependencies, etc.
The changes are the result of running `ng add @angular-eslint/schematics` from the migration guide in https://github.com/angular-eslint/angular-eslint#migrating-an-angular-cli-project-from-codelyzer-and-tslint

**Pull request merged**
