### PR TITLE
Download and upload of SLD files for existing vector layers

### PR DESCRIPTION
**Pull request by raitisbe**
## Description

This PR does several things:
+ Extracts upload file picker / drop zone into separate reusable component which now is used to upload SHP, Geojson, KML and SLD for shapefiles
+ Provides uploading of SLD file in Styler panel for all existing vector layers
+ Refactors existing dynamic generation of downloadable content functionality into a directive, to which a string is given as input and event is emited back with a sanitized href attribute content
+ Provides download button for SLD style in styler panel

## Related issues or pull requests

#2046 
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [x] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [x] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Comment by raitisbe** [comment]
Looks like this:
image

**Comment by fzadrazil** [comment]
Download and upload works fine. But there is an issue regarding the outline color. It gets stored in the form of rgba(...), but it seems that only hexadecimal format is allowed (based on docs and tests in QGIS and GeoServer).

```
<Stroke>
  <CssParameter name="stroke">rgba(56, 179, 251, 0.5)</CssParameter>
</Stroke>
```

Should be
```
<Stroke>
  <CssParameter name="stroke">#38b3fb</CssParameter>
  <CssParameter name="stroke-opacity">0.5</CssParameter>
</Stroke>
```

I have also tried hexadecimal format with alpha channel #rrggbbaa, but QGIS oddly interprets it in different order of #aarrggbb.

**Comment by raitisbe** [comment]
> opacity

Yes, there is some discrepancy between what is parsed and visualized using geostyler/openlayers style parser and what can be used for geoserver. If we store the value in hex we can't fill the colorpickers opacity slider. 

What we can do on hslayers is to give the user ability to specify every parameter and then leave up to the third party parser implementations to deal with it.

Lets move this hex+opacity option to another issue?

**Comment by fzadrazil** [comment]
> Lets move this hex+opacity option to another issue?

#2081

**Review by fzadrazil — APPROVED** [review]

**Pull request merged**
